### ISSUE TITLE
Doesn't work with typescript?

### ISSUE THREAD

**Issue by ArielGueta** [pomber/github-history#13]
https://github-history.netlify.com/angular/angular/blob/master/packages/platform-browser/src/dom/dom_renderer.ts

**Comment by joseluisq** [comment]
https://github-history.netlify.com/ReactiveX/rxjs/blob/master/src/index.ts

![image](https://user-images.githubusercontent.com/1700322/52341530-1d8c7400-2a13-11e9-8d4f-0994730f03ac.png)

BTW: Why is there an unnecessary dumping?

**Comment by pomber** [comment]
I'm using the wrong language name [here](https://github.com/pomber/github-history/blob/master/src/language-detector.js#L4). 
It should be "typescript" instead of "ts". Anyone wanna send a PR?

**Comment by DenVys** [comment]
replaced ts with typescript
sent PR

**Comment by pomber** [comment]
Thanks!
