### ISSUE TITLE
Does it work on private repos?

### ISSUE THREAD

**Issue by wushujames** [pomber/github-history#15]
Hi. Does this work on private repos? What changes would be needed to have it work on private repos?

**Comment by joncasdam** [comment]
It doesn't seem to work on private repos - I just tried and nothing happened.

**Comment by joncasdam** [comment]
maybe if you run it locally and change some things here https://github.com/pomber/github-history/blob/master/src/github.js it could work - but it's just a guess

**Comment by pomber** [comment]
It's related to #9 . I need to add the oauth flow. It shouldn't take too long.

**Comment by pomber** [comment]
It should work now

**Comment by perplexes** [comment]
Does the data from the private repo pass through your server in any way?

**Comment by wushujames** [comment]
Yes, I have the same question as @perplexes.

**Comment by pomber** [comment]
Nope, it goes directly from GitHub to the browser. The access token does pass through Netlify, but I don't think that could be an issue.
