### ISSUE TITLE
Fails on C++ files

### ISSUE THREAD

**Issue by matthew-d-jones** [pomber/github-history#20]
Doesn't seem to work with any C++ files I've tried, despite there being a line for `.cpp` in `language-detector.js`

For example:
https://github-history.netlify.com/ess-dmsc/NeXus-Streamer/blob/master/nexus_file_reader/src/NexusFileReader.cpp

**Comment by pomber** [comment]
Oh, I need to load c before loading cpp. Same happens with jsx and tsx.  
I'll add dependencies to languages.
