### ISSUE TITLE
there is a display bug with chinese

### ISSUE THREAD

**Issue by llyer** [pomber/github-history#21]
![image](https://user-images.githubusercontent.com/16920929/52347345-a4b20a00-2a5c-11e9-9f8e-c93926b417cd.png)

![image](https://user-images.githubusercontent.com/16920929/52347405-cf03c780-2a5c-11e9-871f-fd7839b816f8.png)

Cannot show Chinese language correctly。

url : https://github-history.netlify.com/llyer/leetcode/blob/master/README.md

**Comment by Pierstoval** [comment]
It's not only Chinese: it's unicode characters in general.

I use non-breakable spaces in my code sometimes, and they don't show up properly either:
![image](https://user-images.githubusercontent.com/3369266/52347962-7c59e980-2a23-11e9-9785-546e79984f51.png)
(tested [here](https://github-history.netlify.com/Pierstoval/AgateApps/blob/master/tests/EsterenMaps/Controller/MapsControllerTest.php))

**Comment by llyer** [comment]
> It's not only Chinese: it's unicode characters in general.
> 
> I use non-breakable spaces in my code sometimes, and they don't show up properly either:
> ![image](https://user-images.githubusercontent.com/3369266/52347962-7c59e980-2a23-11e9-9785-546e79984f51.png)
> (tested [here](https://github-history.netlify.com/Pierstoval/AgateApps/blob/master/tests/EsterenMaps/Controller/MapsControllerTest.php))


Ok, understand.

Will you fix this problem?

**Comment by Pierstoval** [comment]
I'm not any maintainer of this project, I just added more details to the issue (= not only chinese but all unicode chars), and I don't know how the project is coded 😄

**Comment by pomber** [comment]
Thanks, I think I know what's the problem, I'll fixit soon

**Comment by pomber** [comment]
#51 should fix this
