### ISSUE TITLE
Doesn't work with scala files

### ISSUE THREAD

**Issue by zanza00** [pomber/github-history#31]
It doesn't works on scala files
https://github-history.netlify.com/scalameta/metals/blob/master/metals/src/main/scala/scala/meta/metals/Main.scala

here is the error

```
index.js:30 TypeError: Cannot set property 'keyword' of undefined
    at Object.extend (prism.js:89)
    at Object.255 (prism-scala.js:1)
    at l (Main.scala:1)
    at Function.l.t (Main.scala:1)
    at  groupOptions: {} namespace object:2446
```

**Comment by pomber** [comment]
Oh, right, because scala depends on java. 
Do you wanna try adding a dependency between scala and java [here](https://github.com/pomber/github-history/blob/master/src/language-detector.js#L62)?
