### ISSUE TITLE
Incorrect prism component for Dockerfiles

### ISSUE THREAD

**Issue by porterdarby** [pomber/github-history#32]
Example: https://github-history.netlify.com/porterdarby/istanbul-tools-docker/blob/master/Dockerfile

The page errors out and produces this in the console:

```
index.js:30 Error: Cannot find module './prism-dockerfile'
    at  groupOptions: {} namespace object:2439
```

I think this is because [prism](https://github.com/PrismJS/prism) has a list of [components](https://github.com/PrismJS/prism/tree/master/components) and the component that you should be loading is [prism-docker](https://github.com/PrismJS/prism/blob/master/components/prism-docker.js) instead of prism-dockerfile.

FIX: Put in an issue/PR with Prism to rename the file OR put in a one-off for docker -> dockerfile OR have a catchall for no syntax highlighting.

**Comment by pomber** [comment]
Wanna send a PR? 

The name of the file comes from this function: https://github.com/pomber/github-history/blob/master/src/language-detector.js#L24

You'd also need to change a test.

**Comment by porterdarby** [comment]
Yep, working on it right now.
