### ISSUE TITLE
Doesn't work with error "Cannot find module './prism-xml'"

### ISSUE THREAD

**Issue by php-coder** [pomber/github-history#47]
It doesn't work for me on the following URL: https://github-history.netlify.com/php-coder/mystamps/blob/master/pom.xml
The error is the following:
```
Error: "Cannot find module './prism-xml'"

    n (index):2439 

index.js:30:8

    314 index.js:30
```
Browser: Firefox 65.0
OS: Windows 10

**Comment by matt-watson90** [comment]
I think I've fixed this in a pull request.  XML and HTML don't have their own prism language packs, they use the markup component instead.

**Comment by php-coder** [comment]
Great! Thanks!
